name: Validate localization files

on:
  workflow_call:
    secrets:
      LOCO_KEY:
        required: true

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8
      - name: Validate
        run: import_loco --check
        env:
          LOCO_API_KEY: ${{ secrets.LOCO_KEY }}
